# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
cloned_from = "https://github.com/fastly/compute-starter-kit-go-tinygo"
description = ""
language = "go"
manifest_version = 3
name = "tiny-go-example"
service_id = ""

[scripts]
  build = "tinygo build -target=wasi -o bin/main.wasm ./"
  env_vars = ["GOARCH=wasm", "GOOS=wasip1"]
  post_init = "go get github.com/fastly/compute-sdk-go@latest"

[local_server]
  [local_server.backends]
    [local_server.backends.www_khanacademy_org]
      url = "https://www.khanacademy.org"
      override_host = "www.khanacademy.org"
