# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
cloned_from = "https://github.com/fastly/compute-starter-kit-typescript"
description = ""
language = "javascript"
manifest_version = 3
name = "ts-example"
service_id = ""

[scripts]
  build = "npm run build"
  post_init = "npm install"

[local_server]
  [local_server.backends]
    [local_server.backends.www_khanacademy_org]
      url = "https://www.khanacademy.org"
      override_host = "www.khanacademy.org"
